name: "Test"

on:
    workflow_dispatch:
      
jobs:
  Test-Echo:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Respository
          uses: actions/checkout@v2

        - name: Echo 
          run: echo "Hello World" 